//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entitiyFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFlight
    {
        public int flightId { get; set; }
        public Nullable<int> flightDeparture { get; set; }
        public Nullable<int> flightArrival { get; set; }
        public Nullable<decimal> flightPrice { get; set; }
        public Nullable<byte> flightCapacity { get; set; }
        public Nullable<System.DateTime> flightDate { get; set; }
        public string flightDescripion { get; set; }
    
        public virtual TblCountry TblCountry { get; set; }
        public virtual TblCountry TblCountry1 { get; set; }
    }
}
