//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entitiyFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPerson
    {
        public int personId { get; set; }
        public string personName { get; set; }
        public string personCity { get; set; }
    }
}
